Repository rust-tutorials/learn-gfx-hal, pull requests merged in 2019-02, with the labels that each got.

#49 URL Fix in lesson 4
  .travis.yml
  book/src/04_triangle_intro.md
Labels: Editing

#52 Instanced drawing example
  examples/instanced_drawing.rs
Labels: Enhancement

#51 Clear The Screen
  book/src/03_clear_the_window.md
  examples/clear_the_screen.rs
Labels: Bug

#55 Add DPI conversion for extents
  book/src/04_triangle_intro.md
  examples/camera.rs
  examples/coordinates.rs
  examples/depth_buffer.rs
  examples/instanced_drawing.rs
  examples/shaders.rs
  examples/textures.rs
  examples/triangle_intro.rs
Labels: Bug

#56 Apply the Clear The screen bug fix to the other lessons
  book/src/03_clear_the_window.md
  book/src/08_camera.md
  examples/camera.rs
  examples/coordinates.rs
  examples/depth_buffer.rs
  examples/shaders.rs
  examples/textures.rs
  examples/triangle_intro.rs
Labels: Bug

#58 Instancing lesson
  Cargo.toml
  book/src/10_instanced_drawing.md
  book/src/images/200kcubes.jpg
  book/src/images/5kcubes.jpg
  examples/instanced_drawing.rs
Labels: Enhancement, Future Lesson

#62 Fix missing link to instancing lesson
  book/src/SUMMARY.md
Labels: Bug

#63 get them off the hook
  book/src/04_triangle_intro.md
Labels: Bug, Editing

#68 Activate Bors!
  .travis.yml
  appveyor.yml
  bors.toml
Labels: Enhancement, Good First Issue, Help Wanted
